### PR TITLE
Bumped Version number to 1.0.5

### PR DESCRIPTION
**Pull request by grthor**
Can be merged as soon as we want to 1.0.5 as version number.

### CODE REVIEW

**Comment by grthor** [comment]
Don't worry about the failed build check. It is caused by the old version bumbers in the crypto repo. They will be replaced by PR https://github.com/jcryptool/crypto/pull/354

**Comment by grthor** [comment]
I will merge the PRs as soon as we want to create the new release.

**Comment by simlei** [comment]
I like this being in the pipeline so to speak :)

**Comment by simlei** [comment]
no problems encountered, signing is in process. Thanks :)

**Pull request merged**
